### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by AntonFriberg** [pwyde/dotfiles#3]
I would really like to use many of your ideas in my own dotfiles. Have you looked into adding a LICENSE to this repo? 

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by pwyde** [comment]
Go for it! There already is a license, mentioned [here](https://github.com/pwyde/dotfiles#page_with_curl-license).

**LICENSE** file is located in the `.github` [directory](https://github.com/pwyde/dotfiles/tree/master/.github). It is located there together with **README.md** file to avoid having a readme and license file in my home directory when using [yadm](https://yadm.io/) for my dotfiles.
